blank_issues_enabled: false
contact_links:
  - name: 💬 GitHub Discussions
    url: https://github.com/[diegopzz]/shieldeye/discussions
    about: For general questions, ideas, and community discussions
  - name: 🔒 Security Issues
    url: https://github.com/[diegopzz]/shieldeye/security
    about: Report security vulnerabilities privately
  - name: 📚 Documentation
    url: https://github.com/[diegopzz]/shieldeye/wiki
    about: Browse the project documentation and guides