'use strict'; // code generated by pbf v3.2.1

// Message ========================================

var Message = self.Message = {};

Message.read = function (pbf, end) {
    return pbf.readFields(Message._readField, {field_01: "", field_02: "", field_03: "", field_04: "", field_05: "", field_06: "", field_07: "", field_08: "", field_09: "", field_10: "", field_11: "", field_12: "", field_13: "", field_14: "", field_15: "", field_16: "", field_17: "", field_18: "", field_19: "", field_20: "", field_21: "", field_22: "", field_23: "", field_24: ""}, end);
};
Message._readField = function (tag, obj, pbf) {
    if (tag === 1) obj.field_01 = pbf.readString();
    else if (tag === 2) obj.field_02 = pbf.readString();
    else if (tag === 3) obj.field_03 = pbf.readString();
    else if (tag === 4) obj.field_04 = pbf.readString();
    else if (tag === 5) obj.field_05 = pbf.readString();
    else if (tag === 6) obj.field_06 = pbf.readString();
    else if (tag === 7) obj.field_07 = pbf.readString();
    else if (tag === 8) obj.field_08 = pbf.readString();
    else if (tag === 9) obj.field_09 = pbf.readString();
    else if (tag === 10) obj.field_10 = pbf.readString();
    else if (tag === 11) obj.field_11 = pbf.readString();
    else if (tag === 12) obj.field_12 = pbf.readString();
    else if (tag === 13) obj.field_13 = pbf.readString();
    else if (tag === 14) obj.field_14 = pbf.readString();
    else if (tag === 15) obj.field_15 = pbf.readString();
    else if (tag === 16) obj.field_16 = pbf.readString();
    else if (tag === 17) obj.field_17 = pbf.readString();
    else if (tag === 18) obj.field_18 = pbf.readString();
    else if (tag === 19) obj.field_19 = pbf.readString();
    else if (tag === 20) obj.field_20 = pbf.readString();
    else if (tag === 21) obj.field_21 = pbf.readString();
    else if (tag === 22) obj.field_22 = pbf.readString();
    else if (tag === 23) obj.field_23 = pbf.readString();
    else if (tag === 24) obj.field_24 = pbf.readString();
};
Message.write = function (obj, pbf) {
    if (obj.field_01) pbf.writeStringField(1, obj.field_01);
    if (obj.field_02) pbf.writeStringField(2, obj.field_02);
    if (obj.field_03) pbf.writeStringField(3, obj.field_03);
    if (obj.field_04) pbf.writeStringField(4, obj.field_04);
    if (obj.field_05) pbf.writeStringField(5, obj.field_05);
    if (obj.field_06) pbf.writeStringField(6, obj.field_06);
    if (obj.field_07) pbf.writeStringField(7, obj.field_07);
    if (obj.field_08) pbf.writeStringField(8, obj.field_08);
    if (obj.field_09) pbf.writeStringField(9, obj.field_09);
    if (obj.field_10) pbf.writeStringField(10, obj.field_10);
    if (obj.field_11) pbf.writeStringField(11, obj.field_11);
    if (obj.field_12) pbf.writeStringField(12, obj.field_12);
    if (obj.field_13) pbf.writeStringField(13, obj.field_13);
    if (obj.field_14) pbf.writeStringField(14, obj.field_14);
    if (obj.field_15) pbf.writeStringField(15, obj.field_15);
    if (obj.field_16) pbf.writeStringField(16, obj.field_16);
    if (obj.field_17) pbf.writeStringField(17, obj.field_17);
    if (obj.field_18) pbf.writeStringField(18, obj.field_18);
    if (obj.field_19) pbf.writeStringField(19, obj.field_19);
    if (obj.field_20) pbf.writeStringField(20, obj.field_20);
    if (obj.field_21) pbf.writeStringField(21, obj.field_21);
    if (obj.field_22) pbf.writeStringField(22, obj.field_22);
    if (obj.field_23) pbf.writeStringField(23, obj.field_23);
    if (obj.field_24) pbf.writeStringField(24, obj.field_24);
};
